#!/bin/bash
#
# nginx <summary>
#
# chkconfig:   2345 80 20
# description: Starts and stops a single nginx instance on this system
#

### BEGIN INIT INFO
# Provides: Nginx
# Required-Start: $network $named
# Required-Stop: $network $named
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: This service manages the nginx daemon
# Description: Nginx is a very scalable, schema-free and high-performance search solution supporting multi-tenancy and near realtime search.
### END INIT INFO

#
# init.d / servicectl compatibility (openSUSE)
#
if [ -f /etc/rc.status ]; then
    . /etc/rc.status
    rc_reset
fi

#
# Source function library.
#
if [ -f /etc/rc.d/init.d/functions ]; then
    . /etc/rc.d/init.d/functions
fi

# Sets the default values for nginx variables used in this script
prog="nginx"

PID_DIR="/var/run/nginx"
PID_DIR="/usr/local/nginx/logs"
pidfile="$PID_DIR/${prog}.pid"
lockfile=/var/lock/subsys/$prog

exec="/usr/local/nginx/sbin/nginx"

if [ ! -x "$exec" ]; then
    echo "The nginx startup script does not exists or it is not executable, tried: $exec"
    exit 1
fi

start() {
    [ -x $exec ]     || exit 5
    [ -f "$lockfile" ] && echo " lockfile exist " && exit 5

    echo -n $"Starting $prog: "
    # if not running, start it up here, usually something like "daemon $exec"
    # daemon --pidfile $pidfile $exec -p $pidfile 
    daemon $exec 
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile
    return $retval
}

stop() {
    echo -n $"Stopping $prog: "
    # stop it here, often "killproc $prog"
    killproc -p $pidfile -d 86400 $prog
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}

restart() {
    stop
    start
}

reload() {
    restart
}

force_reload() {
    restart
}

rh_status() {
    # run checks to determine if the service is running or use generic status
    status -p $pidfile $prog
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}


case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    configtest)
        $exec -t
        ;;
    restart)
        $1
        ;;
    reload)
        rh_status_q || exit 7
        $1
        ;;
    force-reload)
        force_reload
        ;;
    status)
        rh_status
        ;;
    condrestart|try-restart)
        rh_status_q || exit 0
        restart
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload}"
        exit 2
esac
exit $?
