#!/bin/sh

##=======================================================================================
##
##     ----------------------------------
##      SPACE Script for Linux   V2.2
##     ----------------------------------
#
## Copy-Right
## ---------------
#  Copyright couplwith@yahoo.co.kr  Dr.choi in Seoul Korea.
#  since 1999 hanil life insurance - simmani - enkai - haansoft - interpark
#
## Update Note
## ---------------
#   add subdir summery
#            in 2002. 1.  1   : <couplewith@yahoo.co.kr>
#   add sort by summery of size of subdirectory
#            in 2003. 1.  1   : <couplewith@yahoo.co.kr>
#   add installer script v1.0
#            in 2004. 11. 12  : <couplewith@yahoo.co.kr>
#   mod installer script v2.2 : linewidth changed and comment
#            in 2016. 5. 28  : <couplewith@yahoo.co.kr>
#
# # Install guiude 
#
#   This is Shell script with awk (gawk, nawk) and du command.
#   Using "space" is easy find where are usage large files or space in your data storage.
#   This Script show that shell script is a good program for your system management.
#   Imagine for easy and convinence ...
#   Thank you.
#
#   For using "space" by followed some steps:
#   1.Requirement : linux : gawk du (cygwin) / unix nawk, gawk, du
#   2.Download and Save as 
#           : /usr/local/bin/space
#             chmod 755 /usr/local/bin/space
#   3.command and execute : space 
#
#
##=======================================================================================


clear;
echo "";
echo "";
echo "";
df -k ;
APW=`pwd`

#for Sun Server
#du -ok . 2>/dev/null | nawk -F/ -v pas= '
#for Linux Server
#du -Sk . 2>/dev/null | gawk -F/ -v pas= '

du -Sk . 2>/dev/null | gawk -F/ -v pas="$APW" '
    BEGIN {
                    print  "\t\t---------------------------";
                    print  "\t\t DIsk Usae of current Dir";
                    print  "\t\t--------------------------";
                    printf "\t\t [%s] \n\n", pas;

                    printf"\t%-50s : %10s   : %10s \n","------------------",
				   			"----------","---------";
                    printf"\t%-50s : %10s   : %10s \n","DIRNAME", "SIZE (MB)","Subdir cnt";
                    printf"\t%-50s : %10s   : %10s \n","------------------",
				   			"----------","---------";
               tots=0;
               tcnt=0;
               i=0;
           }
           {
                pos=index($1, ".");
                size=substr($1,1, pos-1);

                tcnt++;
                tots+=size;

                if ( NR ==1 )
                {
                    dirs=$2;
                    dsize=0;
                    dcnt=0;
                }

                if ( dirs == $2 )
                {
                    dsize+=size;
                    dcnt++;
                }
                else
                {
                  # printf"\t%-50s : %10.2fMB : %10d \n",dirs, dsize/1024, dcnt;
                    DIR[i]= dirs;
                    Dsize[i]=dsize/1024;
                    Dcnt[i]=dcnt;

                    dirs=$2;
                    dsize=size;
                    dcnt=1;
                    i = i + 1;
                }

            }
        END {
                    DIR[i]  = "./";
                    Dsize[i]=dsize/1024;
                    Dcnt[i]=dcnt;

                    # SORT SECTION
                    for ( j=0; j<i ; j++ )
                    {
                        for ( k=j+1; k<=i ; k++ )
                        {
                           if ( Dsize[j] > Dsize [k]){
                               tmp1=DIR[j];
                               tmp2=Dsize[j];
                               tmp3=Dcnt[j];

                               DIR[j]=DIR[k];
                               Dsize[j]=Dsize[k];
                               Dcnt[j]=Dcnt[k];

                               DIR[k]=tmp1;
                               Dsize[k]=tmp2;
                               Dcnt[k]=tmp3;
                           }
                        }
                    }

                    # PRINT SECTION
                    for ( j=0; j<=i ; j++ )
                    {
                        printf"\t%-50s : %10.2fMB : %10d \n",DIR[j], Dsize[j], Dcnt[j];
                    }
                    printf"\t%-50s : %10s   : %10s \n","------------------",
				   			"----------","---------";
                    printf"\t%-50s : %10.2fMB : %10d \n","TOTALSIZE", tots/1024, tcnt;
                    printf"\t%-50s : %10s   : %10s \n","------------------",
				   			"----------","---------";
                    printf"\t      --  Copy Right @ Choi Doo Rip  1999  --  \n"

            }'
