CREATE TABLE `insert_myisam` (
  `seq` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20)  DEFAULT NULL,
  `regdate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`seq`)
) ENGINE=MYISAM DEFAULT CHARSET=utf8 COLLATE=utf8_croatian_ci;


CREATE TABLE `insert_innodb` (
  `seq` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20)  DEFAULT NULL,
  `regdate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`seq`)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COLLATE=utf8_croatian_ci;


CREATE TABLE `insert_tokudb` (
  `seq` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) DEFAULT NULL,
  `regdate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`seq`)
) ENGINE=TokuDB DEFAULT CHARSET=utf8 COLLATE=utf8_croatian_ci;